//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHungerAgnmt.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string AccountType { get; set; }
    
        public virtual Account Accounts1 { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
